#配置数据源
spring:

  datasource:
    blueray:
      url: jdbc:mysql://localhost:3306/blueray?useUnicode=true&characterEncoding=utf8
      username: root
      password: root123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      mapper-location: classpath:mybatis/mapper/taobao/blueray/*.xml
      mapper-package: com.yq.blueray.taobao.dao.mysql
    sqlserver:
      url: jdbc:sqlserver://192.168.1.200:1433;Database=mpdisk
      username: sa
      password: nankai.2017
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      type: com.alibaba.druid.pool.DruidDataSource
      mapper-location: classpath:mybatis/mapper/taobao/sqlserver/*.xml
      mapper-package: com.yq.blueray.taobao.dao.sqlserver
  path:
    csv: classpath:object-excel/csv/

  thymeleaf:
    cache: false
    prefix: classpath:templates/html/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5

    servlet:
      content-type: text/html
      multipart:
        enabled: true
        resolve-lazily: true
        max-file-size: 100MB

  mvc:
    static-path-pattern: /static/**

  resources: classpath:/static/**

#指定mybatis映射文件的地址
mybatis:
  #mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yq.blueray.taobao.entity

#服务器设置
server:
  port: 8080
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 50Mb

#日志设置
logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: debug
    com.howtodoinjava: INFO
    org.hibernate: ERROR


